connect to API pull request
theresetuyi/React-Bookstore pull request #7
Opened 2023-06-14 22:48 UTC by theresetuyi

## Bookstore: connect to API
Use the concept of state management.
Use store, actions and reducers in React.
Connect React and Redux.
Connect an existing API via Redux and use the data to display something in a UI.

2023-06-15 00:08 UTC, Davidosky007 requested changes
Hi @theresetuyi 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
* Store, actions and reducers in used 👍 
* Redux setup properly 👍 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidsoky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-15 00:08 UTC, Davidosky007 commented on src/BooksApi/BooksApi.js
> +  return response.data;
* I get this error in the console when I try to add a book, Kindly fix it as the API doesn't function like it should 
![image](https://github.com/theresetuyi/React-Bookstore/assets/52497246/63fd0698-2ed0-495d-a6b7-95578c54adc2)

2023-06-15 00:08 UTC, Davidosky007 commented on src/redux/books/booksSlice.js
> +  // console.log(response, 'this is api data');
* Kindly remove all commented code form your code base as it makes your code bulky

2023-06-15 14:00 UTC, FrederickMih requested changes
## Hi :raising_hand: :raising_hand: @theresetuyi , 


Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

- No Linter failure  :+1: 
- PR is descriptive :+1: 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-15 14:00 UTC, FrederickMih commented on src/redux/books/booksSlice.js
>  export const fetchBooksAsync = createAsyncThunk('books/fetchBooks', async () => {
- [ ] Kindly make sure that fetchBooksAsync actually updates the state of booksSlice. Right now I'm still unable to add a book. Only the default books from the books array are displayed. Kindly make sure it is possible to add a book.

[Screencast from 06-15-2023 02:56:32 PM.webm](https://github.com/theresetuyi/React-Bookstore/assets/63087491/24c9eeac-1688-4f02-a3d4-4e39ecaa730d)

2023-06-16 17:41 UTC, ridwanediallo approved these changes
# STATUS: APPROVED 🟢
## Hi @theresetuyi , 
![Congratulations!GIF](https://user-images.githubusercontent.com/55918904/191301390-43d62dfa-bfdc-49c5-943b-4d72f4ea5bb8.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used GitHub flow correctly. ✔
- Well done implementing the changes requested by the previous reviewer. ✔
- You successfully completed all the requirements.  🎉 🎉 🎉 ✔

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-16 17:46 UTC, merged